#pragma once

#include <string>

namespace san::cmake {

[[maybe_unused]] static std::string compile_opts()	{ return "-O3 -DNDEBUG -mavx2 -Wall -fno-exceptions -fno-rtti"; }
[[maybe_unused]] static std::string build_type()	{ return "Release"; }

// Not generated by cmake, but let it be here.
[[maybe_unused]] static std::string compiler_id() {
#if defined( __clang__ ) // Clang also defines __GNUG__ (why?). So i'll check for '__clang__' first.
	return __VERSION__;
#elif defined( __GNUG__ )
	return "GNU C++ " + std::to_string( __GNUC__ ) + '.' + std::to_string( __GNUC_MINOR__ ) + '.' + std::to_string( __GNUC_PATCHLEVEL__ );
#else // other trash...
	return "Clang";
#endif
}

#if 0
[[maybe_unused]] static std::string SIMD_supported() { return
#ifdef __SSE__
	" SSE"
#endif

#ifdef __SSE2__
	" SSE2"
#endif

#ifdef __SSE3__
	" SSE3"
#endif

#ifdef __SSSE3__
	" SSSE3"
#endif

#ifdef __SSE4_1__
	" SSE4.1"
#endif

#ifdef __SSE4_2__
	" SSE4.2"
#endif

#ifdef __SSE4A__
	" SSE4A"
#endif

#ifdef __AVX__
	" AVX"
#endif

#ifdef __AVX2__
	" AVX2"
#endif

#ifdef __FMA__
	" FMA"
#endif
	;
}
#endif

} // namespace san::cmake
